image:
  repository: maxmorhardt/topfilms-primary-api
  tag: '1.0.0'
  pullPolicy: Always
  env:
    - name: spring.datasource.url
      valueFrom:
        secretKeyRef:
          name: primary-api-env
          key: dbUsername
    - name: spring.datasource.username
      valueFrom:
        secretKeyRef:
          name: primary-api-env
          key: dbPassword
    - name: spring.datasource.password
      valueFrom:
        secretKeyRef:
          name: primary-api-env
          key: datasourceUrl

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.topfilms.io
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: api.topfilms.io-tls
     hosts:
       - api.topfilms.io

resources:
  limits:
    cpu: 512m
    memory: 256Mi
  requests:
    cpu: 512m
    memory: 256Mi
